using WKAppBot.Core.Scenario;
using WKAppBot.Win32.Input;
using WKAppBot.Win32.Window;

namespace WKAppBot.Core.Runner;

public sealed partial class ActionExecutor
{
    // -- Screenshot --------------------------------------------─

    private void DoScreenshot(StepDefinition step, StepResult result)
    {
        // Output path resolution:
        //   1) params.path  -> use verbatim (caller owns directory + filename)
        //   2) params.filename -> legacy: drop into output/screenshots/
        //   3) autogenerated timestamped filename under output/screenshots/
        string fullPath;
        if (!string.IsNullOrWhiteSpace(step.Params?.Path))
        {
            fullPath = step.Params!.Path!;
            var dir = System.IO.Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrEmpty(dir))
                Directory.CreateDirectory(dir);
        }
        else
        {
            var filename = step.Params?.Filename ?? $"step_{DateTime.Now:yyyyMMdd_HHmmss}.png";
            var outputDir = System.IO.Path.Combine("output", "screenshots");
            Directory.CreateDirectory(outputDir);
            fullPath = System.IO.Path.Combine(outputDir, filename);
        }

        var captionForLog = System.IO.Path.GetFileName(fullPath);

        // Window resolution:
        //   target.class_name -> WindowFinder.FindByClassName (first visible match)
        //   fallback          -> _ctx.MainWindowHandle (legacy behavior)
        IntPtr hWnd = _ctx.MainWindowHandle;
        string? resolvedVia = null;
        if (!string.IsNullOrWhiteSpace(step.Target?.ClassName))
        {
            var cls = step.Target!.ClassName!;
            var matches = WindowFinder.FindByClassName(cls);
            if (matches.Count > 0)
            {
                hWnd = matches[0].Handle;
                resolvedVia = $"class_name=\"{cls}\" -> hwnd:0x{hWnd.ToInt64():X8}";
                Log($"  Screenshot: resolved {resolvedVia}");
            }
            else
            {
                Log($"  Screenshot: class_name=\"{cls}\" not found, falling back to main window");
            }
        }

        if (hWnd == IntPtr.Zero)
        {
            result.Status = StepStatus.Fail;
            result.Message = "Screenshot: no window handle available (main handle empty and class_name unresolved)";
            Log("  " + result.Message);
            return;
        }

        // screenshot: set action point to window center
        SetActionPointToWindowCenter(step.Name, "screenshot", captionForLog);

        using var bmp = ScreenCapture.CaptureWindow(hWnd, new WKAppBot.Win32.Input.CaptureOptions
        {
            RejectBlank = true,
            StepLogger = Log,
        });
        if (bmp == null)
        {
            result.Status = StepStatus.Fail;
            result.Message = $"Screenshot: blank/failed capture for {captionForLog}";
            Log("  " + result.Message);
            return;
        }
        ScreenCapture.SaveToFile(bmp, fullPath);

        result.ScreenshotPath = fullPath;
        result.Status = StepStatus.Pass;
        result.Message = $"Saved: {fullPath}";
        result.ActionDetail = resolvedVia != null
            ? $"Screenshot -> {captionForLog} ({resolvedVia})"
            : $"Screenshot -> {captionForLog}";
        Log($"  Screenshot: {fullPath}");
    }
}
