name: Lint Check

on:
  pull_request:
    paths: ['csharp/**']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  format:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4

    - name: Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7  # v5
      with:
        dotnet-version: 8.0.x

    - name: Check formatting (launcher)
      shell: pwsh
      run: |
        dotnet format csharp/src/WKAppBot.Launcher/WKAppBot.Launcher.csproj `
          --verify-no-changes --verbosity diagnostic
